logpath = "log/"
id = 103
immitator = false #если истина то запускать имитатор 
[server]
host = "asdu.tech"
port = 1093
[pudge]
dbpath = "db/"
[modbus]
device = "rtu:///dev/com1"
baudrate = 19200
parity = "N"
uid = 247
[modbusradar]
radar = false           #если истинно нужно открывать прием сигналов радара
master = true
debug = false
host = "178.176.55.215"
port = 15001
id = 11
chanels = 16
[visiodevice]
visio = false           #если истино то есть индикаторы обратного отсчета
device = "/dev/ttyUSB0"
baudrate = 19200
parity = "N"
[trafficdata]
work = false
debug = false      #Запускать иммитатор
host = "127.0.0.1"
port = 1666
listen = 1667
chanels = 16
