logpath = "log/"
id = 101
# id = 198460 #Номер устройства дома
# id=230412
# id=108682			#Номер в Элисте
immitator = false #если истина то запускать имитатор 
[server]
# host = "asdu.tech"
# host = "10.151.50.126"
# host = "192.168.2.156"
host = "192.168.88.2"
port = 1093
[pudge]
dbpath = "db/"
[modbus]
# device="rtu:///dev/ttyUSB0"
# device = "rtu:///dev/ttyEXTRA2_00"
device = "rtu:///dev/com1"
baudrate = 19200
parity = "N"
uid = 247
[modbusradar]
radar = true            #если истинно нужно открывать прием сигналов радара
master = true
debug = false
host = "178.176.55.215"
# host = "127.0.0.1"
port = 15001
id = 11
chanels = 16
[visiodevice]
visio = false           #если истино то есть индикаторы обратного отсчета
device = "/dev/ttyUSB0"
#device="rtu:///dev/ttyEXTRA2_00"
baudrate = 19200
parity = "N"
[trafficdata]
work = false
debug = true       #Запускать иммитатор
host = "127.0.0.1"
port = 1666
listen = 1667
chanels = 16
